const cfg=window.TRADEFORGE_CONFIG||{};let supabaseClient=null,session=null,trades=[];
const emotions=["Calm","Focused","Confident","Patient","Excited","Anxious","Fearful","Frustrated","Angry","Bored","Impatient","Overconfident","Hesitant","Hopeful","Confused"];
const mistakes=["FOMO entry","Revenge trade","Overtrading","Oversizing","Moved stop","Moved target","Early entry","Late entry","Chased price","Ignored setup rules","Traded outside plan","Wrong session","No confirmation","Ignored higher timeframe","Entered during news","Ignored risk limit","Exited emotionally","Held loser too long","Cut winner early","No clear invalidation"];
const $=id=>document.getElementById(id),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function avg(a){return a.length?a.reduce((x,y)=>x+Number(y||0),0)/a.length:0}
function fmt(n){return Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:2})}
async function init(){if(!cfg.SUPABASE_URL||cfg.SUPABASE_URL.startsWith("YOUR_")){$("authMsg").textContent="Add your Supabase URL and publishable/anon key in config.js first.";return}supabaseClient=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);const r=await supabaseClient.auth.getSession();session=r.data.session;if(session)startApp();supabaseClient.auth.onAuthStateChange((_e,s)=>{session=s;s?startApp():showAuth()})}
function showAuth(){$("authScreen").classList.remove("hidden");$("app").classList.add("hidden")}
function startApp(){$("authScreen").classList.add("hidden");$("app").classList.remove("hidden");loadTrades();go("dashboard")}
async function loadTrades(){const r=await supabaseClient.from("trades").select("*").order("traded_at",{ascending:false});if(r.error){$("saveStatus").textContent="● Database error";return}trades=r.data||[];renderPage()}
function go(page){document.querySelectorAll(".nav").forEach(b=>b.classList.toggle("active",b.dataset.page===page));const names={dashboard:["OVERVIEW","Dashboard"],journal:["JOURNAL","Trade Journal"],newtrade:["EXECUTION","New Trade"],psychology:["PSYCHOLOGY","Psychology"],mistakes:["BEHAVIOR","Mistake Intelligence"],analytics:["ANALYTICS","Performance Analytics"],review:["REVIEW","Review Center"],settings:["ACCOUNT","Settings"]};$("pageKicker").textContent=names[page][0];$("pageTitle").textContent=names[page][1];const t=$(page+"Tpl");$("content").innerHTML=t?t.innerHTML:"";if(page==="newtrade")renderTradeForm();else if(page==="dashboard")renderDashboard();else if(page==="journal")renderJournal();else if(page==="psychology")renderPsych();else if(page==="mistakes")renderMistakes();else if(page==="analytics")renderAnalytics();else if(page==="review")renderReview();else if(page==="settings")renderSettings()}
function renderPage(){if(!$("app").classList.contains("hidden")){const p=document.querySelector(".nav.active")?.dataset.page||"dashboard";if(p!=="newtrade")go(p)}}
function chips(id,items){$(id).innerHTML=items.map((x,i)=>'<button type="button" class="chip" data-chip="'+id+'" data-val="'+esc(x)+'">'+esc(x)+'</button>').join("")}
function renderTradeForm(){let d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());$("tDate").value=d.toISOString().slice(0,16);chips("emotionChips",emotions);chips("mistakeChips",mistakes);document.querySelectorAll("[data-chip]").forEach(b=>b.onclick=()=>b.classList.toggle("selected"));["greed","fear","fomo","revenge","confidence","disc"].forEach(x=>{const el=$("t"+x.charAt(0).toUpperCase()+x.slice(1));if(el)el.oninput=()=>$(x+"Out").textContent=el.value});$("tradeForm").onsubmit=saveTrade}
async function saveTrade(e){e.preventDefault();const get=id=>$(id)?.value||"";const selected=id=>[...document.querySelectorAll('[data-chip="'+id+'"].selected')].map(x=>x.dataset.val);const row={user_id:session.user.id,traded_at:new Date(get("tDate")).toISOString(),symbol:get("tSymbol").trim().toUpperCase(),market:get("tMarket"),direction:get("tDirection"),session:get("tSession"),period_quality:get("tPeriod"),setup:get("tSetup"),market_condition:get("tCondition"),entry:+get("tEntry")||null,stop_loss:+get("tSL")||null,take_profit:+get("tTP")||null,exit_price:+get("tExit")||null,risk_amount:+get("tRisk")||0,pnl:+get("tPnl")||0,r_multiple:+get("tR")||0,result:get("tResult"),greed:+get("tGreed"),fear:+get("tFear"),fomo:+get("tFomo"),revenge:+get("tRevenge"),confidence:+get("tConfidence"),discipline:+get("tDiscipline"),emotions:selected("emotionChips"),mistakes:selected("mistakeChips"),followed_plan:$("cPlan").checked,correct_risk:$("cRisk").checked,good_entry:$("cEntry").checked,good_exit:$("cExit").checked,correct_session:$("cSession").checked,patience:$("cPatience").checked,notes:get("tNotes"),lesson:get("tLesson")};$("saveTrade").disabled=true;$("saveTrade").textContent="Saving…";const r=await supabaseClient.from("trades").insert(row);if(r.error){$("tradeMsg").textContent=r.error.message;$("saveTrade").disabled=false;$("saveTrade").textContent="Save trade & update analytics";return}await loadTrades();$("saveStatus").textContent="● Saved to cloud";go("dashboard")}
function renderDashboard(){const t=trades,n=t.length,pnl=t.reduce((a,x)=>a+Number(x.pnl||0),0),wins=t.filter(x=>x.result==="Win").length;const psych=n?avg(t.map(x=>(x.confidence+x.discipline+(11-x.greed)+(11-x.fear)+(11-x.fomo)+(11-x.revenge))/6)):0;const discipline=n?avg(t.map(x=>[x.followed_plan,x.correct_risk,x.good_entry,x.good_exit,x.correct_session,x.patience].filter(Boolean).length/6*10)):0; $("dPnl").textContent="₹"+fmt(pnl);$("dWin").textContent=n?Math.round(wins/n*100)+"%":"0%";$("dR").textContent=fmt(avg(t.map(x=>x.r_multiple)))+"R";$("dTrades").textContent=n;$("dPsych").textContent=n?fmt(psych):"—";$("dGreed").textContent=n?fmt(avg(t.map(x=>x.greed))):"—";$("dashDiscipline").textContent=n?Math.round(discipline*10)+"%":"—";$("dashDisciplineSub").textContent=n?"Execution rule score":"Based on rule-following";$("coachHeadline").textContent=n?psych<5?"Your psychology needs attention.":"Keep turning trades into evidence.":"Turn every trade into feedback.";renderBars("psychBars",[{n:"Discipline",v:avg(t.map(x=>x.discipline))},{n:"Confidence",v:avg(t.map(x=>x.confidence))},{n:"Greed",v:avg(t.map(x=>x.greed))},{n:"Fear",v:avg(t.map(x=>x.fear))},{n:"FOMO",v:avg(t.map(x=>x.fomo))},{n:"Revenge",v:avg(t.map(x=>x.revenge))}]);renderMistakeMini();renderSessions()}
function renderBars(id,arr){$(id).innerHTML=arr.map(x=>'<div class="bar-row"><span>'+x.n+'</span><div class="bar"><i style="width:'+Math.min(100,x.v*10)+'%"></i></div><b>'+fmt(x.v)+'</b></div>').join("")||'<p class="muted">No trades yet.</p>'}
function renderMistakeMini(){const map={};trades.forEach(t=>(t.mistakes||[]).forEach(m=>{map[m]??={count:0,pnl:0};map[m].count++;map[m].pnl+=+t.pnl||0}));const a=Object.entries(map).sort((x,y)=>Math.abs(y[1].pnl)-Math.abs(x[1].pnl)).slice(0,5);$("mistakeList").innerHTML=a.length?a.map(([m,v])=>'<div class="analysis-card"><b>'+esc(m)+'</b><span class="muted">'+v.count+' occurrence(s) · ₹'+fmt(v.pnl)+' P&L impact</span></div>').join(""):'<p class="muted">No mistakes tagged yet.</p>'}
function renderSessions(){const map={};trades.forEach(t=>{map[t.session]??=[];map[t.session].push(t)});$("sessionTable").innerHTML=Object.keys(map).length?'<table class="data-table"><tr><th>Session</th><th>Trades</th><th>Win rate</th><th>Avg R</th><th>Avg greed</th><th>Period quality</th></tr>'+Object.entries(map).map(([s,a])=>'<tr><td>'+esc(s)+'</td><td>'+a.length+'</td><td>'+Math.round(a.filter(x=>x.result==="Win").length/a.length*100)+'%</td><td>'+fmt(avg(a.map(x=>x.r_multiple)))+'R</td><td>'+fmt(avg(a.map(x=>x.greed)))+'</td><td>'+Math.round(a.filter(x=>x.period_quality==="right").length/a.length*100)+'%</td></tr>').join("")+'</table>':'<p class="muted">Add trades to see session intelligence.</p>'}
function renderJournal(){const draw=()=>{const q=($("searchTrades")?.value||"").toLowerCase(),f=$("filterResult")?.value||"";const a=trades.filter(t=>(!f||t.result===f)&&(!q||(t.symbol+" "+t.setup+" "+(t.mistakes||[]).join(" ")).toLowerCase().includes(q)));$("journalTable").innerHTML='<div style="overflow:auto"><table class="data-table"><tr><th>Date</th><th>Symbol</th><th>Session</th><th>Result</th><th>P&L</th><th>R</th><th>Psych</th><th>Greed</th><th>Mistakes</th></tr>'+a.map(t=>'<tr><td>'+new Date(t.traded_at).toLocaleString()+'</td><td><b>'+esc(t.symbol)+'</b><br><small>'+esc(t.setup)+'</small></td><td>'+esc(t.session)+'</td><td>'+esc(t.result)+'</td><td class="'+(t.pnl>=0?"positive":"negative")+'">₹'+fmt(t.pnl)+'</td><td>'+fmt(t.r_multiple)+'R</td><td>'+fmt((t.confidence+t.discipline+(11-t.greed)+(11-t.fear)+(11-t.fomo)+(11-t.revenge))/6)+'</td><td>'+t.greed+'/10</td><td>'+esc((t.mistakes||[]).join(", "))+'</td></tr>').join("")+'</table></div>'};draw();$("searchTrades").oninput=draw;$("filterResult").onchange=draw}
function renderPsych(){
  const t=trades||[],n=t.length;
  const mean=key=>n?avg(t.map(x=>Number(x?.[key]||0))):0;
  const score=n?avg(t.map(x=>{
    const greed=Number(x.greed)||0,fear=Number(x.fear)||0,fomo=Number(x.fomo)||0,revenge=Number(x.revenge)||0,confidence=Number(x.confidence)||0,discipline=Number(x.discipline)||0;
    return (confidence+discipline+(11-greed)+(11-fear)+(11-fomo)+(11-revenge))/6;
  })):0;
  $("pOverall").textContent=n?fmt(score):"—";
  $("pGreed").textContent=n?fmt(mean("greed"))+" / 10":"—";
  $("pFear").textContent=n?fmt(mean("fear"))+" / 10":"—";
  $("pFomo").textContent=n?fmt(mean("fomo"))+" / 10":"—";
  $("pRevenge").textContent=n?fmt(mean("revenge"))+" / 10":"—";
  $("pDisc").textContent=n?fmt(mean("discipline"))+" / 10":"—";
  renderBars("psychTrend",[
    {n:"Confidence average",v:mean("confidence")},
    {n:"Discipline average",v:mean("discipline")},
    {n:"Greed average",v:mean("greed")},
    {n:"Fear average",v:mean("fear")},
    {n:"FOMO average",v:mean("fomo")},
    {n:"Revenge average",v:mean("revenge")}
  ]);
  const em={};
  t.forEach(x=>(Array.isArray(x.emotions)?x.emotions:[]).forEach(e=>{em[e]??=[];em[e].push(x)}));
  $("emotionAnalysis").innerHTML=Object.entries(em).sort((a,b)=>b[1].length-a[1].length).map(([e,a])=>
    '<div class="analysis-card"><b>'+esc(e)+'</b><span>'+a.length+' trades · '+Math.round(a.filter(x=>x.result==="Win").length/a.length*100)+'% win · '+fmt(avg(a.map(x=>Number(x.r_multiple)||0)))+'R avg · ₹'+fmt(avg(a.map(x=>Number(x.pnl)||0)))+' avg P&L</span></div>'
  ).join("")||'<p class="muted">No emotions have been tagged yet.</p>';
  const warningRows=[
    ["Greed","greed"],["Fear","fear"],["FOMO","fomo"],["Revenge urge","revenge"],["Confidence","confidence"],["Discipline","discipline"]
  ];
  $("psychWarnings").innerHTML=n?
    '<div class="analysis-card"><b>Average psychology from all saved trades</b><span>'+n+' trade'+(n===1?'':'s')+' included · Overall score '+fmt(score)+'/10</span></div>'+
    warningRows.map(([label,key])=>'<div class="analysis-card"><b>'+label+'</b><span>Average: '+fmt(mean(key))+'/10 · '+(mean(key)>=7?'High':mean(key)>=4?'Moderate':'Low')+'</span></div>').join("")
    :'<p class="muted">Save at least one trade to generate psychology averages.</p>';
  const byResult={};
  t.forEach(x=>{const r=x.result||"Unknown";byResult[r]??=[];byResult[r].push(x)});
  const resultHtml=Object.entries(byResult).map(([r,a])=>
    '<div class="analysis-card"><b>'+esc(r)+'</b><span>'+a.length+' trades · Avg greed '+fmt(avg(a.map(x=>Number(x.greed)||0)))+'/10 · Avg fear '+fmt(avg(a.map(x=>Number(x.fear)||0)))+'/10 · Avg discipline '+fmt(avg(a.map(x=>Number(x.discipline)||0)))+'/10 · Avg P&L ₹'+fmt(avg(a.map(x=>Number(x.pnl)||0)))+'</span></div>'
  ).join("");
  const session={};
  t.forEach(x=>{const ss=x.session||"Unspecified";session[ss]??=[];session[ss].push(x)});
  const sessionHtml=Object.entries(session).map(([ss,a])=>
    '<div class="analysis-card"><b>'+esc(ss)+'</b><span>'+a.length+' trades · Avg greed '+fmt(avg(a.map(x=>Number(x.greed)||0)))+'/10 · Avg fear '+fmt(avg(a.map(x=>Number(x.fear)||0)))+'/10 · Avg FOMO '+fmt(avg(a.map(x=>Number(x.fomo)||0)))+'/10 · Avg discipline '+fmt(avg(a.map(x=>Number(x.discipline)||0)))+'/10</span></div>'
  ).join("");
  if(n){
    $("psychWarnings").innerHTML+='<div class="analysis-card"><b>Psychology by result</b>'+resultHtml+'</div><div class="analysis-card"><b>Psychology by trading session</b>'+sessionHtml+'</div>';
  }
}
function renderMistakes(){const map={};trades.forEach(t=>(t.mistakes||[]).forEach(m=>{map[m]??={trades:[],pnl:0};map[m].trades.push(t);map[m].pnl+=+t.pnl||0}));const a=Object.entries(map).sort((x,y)=>Math.abs(y[1].pnl)-Math.abs(x[1].pnl));$("mistakeAnalysis").innerHTML=a.length?a.map(([m,v])=>'<div class="analysis-card"><b>'+esc(m)+'</b><span>'+v.trades.length+' times · ₹'+fmt(v.pnl)+' total P&L · '+Math.round(v.trades.filter(x=>x.result==="Win").length/v.trades.length*100)+'% win rate · avg '+fmt(avg(v.trades.map(x=>x.r_multiple)))+'R</span></div>').join(""):'<p class="muted">No mistakes tagged. Honest tagging is essential.</p>';const rule=trades.filter(t=>t.followed_plan),bad=trades.filter(t=>!t.followed_plan);$("ruleAnalysis").innerHTML='<div class="analysis-card"><b>Followed plan</b><span>'+rule.length+' trades · '+(rule.length?Math.round(rule.filter(x=>x.result==="Win").length/rule.length*100):0)+'% win · '+fmt(avg(rule.map(x=>x.r_multiple)))+'R avg</span></div><div class="analysis-card"><b>Did not follow plan</b><span>'+bad.length+' trades · '+(bad.length?Math.round(bad.filter(x=>x.result==="Win").length/bad.length*100):0)+'% win · '+fmt(avg(bad.map(x=>x.r_multiple)))+'R avg</span></div>'}
function renderAnalytics(){const t=trades,n=t.length,w=t.filter(x=>x.result==="Win"),l=t.filter(x=>x.result==="Loss");const metrics=[["Profit factor",l.length?fmt(w.reduce((a,x)=>a+x.pnl,0)/Math.abs(l.reduce((a,x)=>a+x.pnl,0))):"—"],["Expectancy / trade","₹"+fmt(avg(t.map(x=>x.pnl)))],["Avg winner","₹"+fmt(avg(w.map(x=>x.pnl)))],["Avg loser","₹"+fmt(avg(l.map(x=>x.pnl)))],["Win rate",n?Math.round(w.length/n*100)+"%":"0%"],["Avg R",fmt(avg(t.map(x=>x.r_multiple)))+"R"],["Right-period trades",n?Math.round(t.filter(x=>x.period_quality==="right").length/n*100)+"%":"0%"],["Rule-following",n?Math.round(t.filter(x=>x.followed_plan).length/n*100)+"%":"0%"]];$("analyticsGrid").innerHTML=metrics.map(x=>'<div class="stat"><span>'+x[0]+'</span><b>'+x[1]+'</b></div>').join("");renderGroup("strategyAnalysis","setup");renderGroup("timeAnalysis","session")}
function renderGroup(id,key){const map={};trades.forEach(t=>{const k=t[key]||"Unspecified";map[k]??=[];map[k].push(t)});$(id).innerHTML=Object.entries(map).sort((a,b)=>b[1].length-a[1].length).map(([k,a])=>'<div class="analysis-card"><b>'+esc(k)+'</b><span>'+a.length+' trades · '+Math.round(a.filter(x=>x.result==="Win").length/a.length*100)+'% win · '+fmt(avg(a.map(x=>x.r_multiple)))+'R avg · ₹'+fmt(a.reduce((z,x)=>z+x.pnl,0))+' total</span></div>').join("")||'<p class="muted">No data yet.</p>'}
function renderReview(){if(!trades.length){$("reviewContent").innerHTML='<div class="analysis-card">Log a few trades first. Your review center will identify recurring behaviors.</div>';return}const mistakes={};trades.forEach(t=>(t.mistakes||[]).forEach(m=>mistakes[m]=(mistakes[m]||0)+1));const top=Object.entries(mistakes).sort((a,b)=>b[1]-a[1])[0];const worst=[...trades].sort((a,b)=>a.pnl-b.pnl)[0],best=[...trades].sort((a,b)=>b.pnl-a.pnl)[0];$("reviewContent").innerHTML='<div class="analysis-card"><b>Most repeated behavior</b><span>'+(top?esc(top[0])+" — "+top[1]+" times":"None yet")+'</span></div><div class="analysis-card"><b>Worst trade to review</b><span>'+(worst?esc(worst.symbol)+" · ₹"+fmt(worst.pnl)+" · "+esc((worst.lesson||worst.notes||"No lesson recorded")):"—")+'</span></div><div class="analysis-card"><b>Best trade to study</b><span>'+(best?esc(best.symbol)+" · ₹"+fmt(best.pnl)+" · "+esc((best.lesson||best.notes||"No lesson recorded")):"—")+'</span></div>'}
function renderSettings(){$("accountEmail").textContent=session.user.email; $("exportBtn").onclick=()=>download("tradeforge-trades.csv",csv());$("backupBtn").onclick=()=>download("tradeforge-backup.json",JSON.stringify(trades,null,2),"application/json")}
function csv(){if(!trades.length)return "No trades";const keys=Object.keys(trades[0]);return [keys.join(","),...trades.map(t=>keys.map(k=>'"'+String(t[k]??"").replaceAll('"','""')+'"').join(","))].join("\n")}
function download(name,data,type="text/csv"){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
document.addEventListener("click",e=>{const b=e.target.closest("[data-page]");if(b)go(b.dataset.page);const p=e.target.closest("[data-page-action]");if(p)go(p.dataset.pageAction)});
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");const signup=b.dataset.mode==="signup";$("authBtn").textContent=signup?"Create account":"Log in";$("password").autocomplete=signup?"new-password":"current-password";$("authForm").dataset.mode=b.dataset.mode});
$("authForm").onsubmit=async e=>{e.preventDefault();if(!supabaseClient)return;const email=$("email").value,password=$("password").value,signup=$("authForm").dataset.mode==="signup";$("authMsg").textContent="";const r=signup?await supabaseClient.auth.signUp({email,password}):await supabaseClient.auth.signInWithPassword({email,password});if(r.error)$("authMsg").textContent=r.error.message;else if(signup)$("authMsg").textContent="Account created. Check your email if confirmation is enabled."};
$("resetBtn").onclick=async()=>{if(!supabaseClient)return;const email=$("email").value;if(!email){$("authMsg").textContent="Enter your email first.";return}const r=await supabaseClient.auth.resetPasswordForEmail(email,{redirectTo:location.href});$("authMsg").textContent=r.error?r.error.message:"Password reset email sent."};
$("logoutBtn").onclick=()=>supabaseClient.auth.signOut();
init();